#!/bin/bash

make clean
make CFLAGS='-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -fembed-bitcode-marker -DVESMAIL_APP_BUILD=ios'
mv libvesmail.a libvesmail-ioss-arm64.a
cp /Users/test1/libVES.c/lib*-ioss-arm64.a .
cp /Users/test1/openssl/lib*-ioss-arm64.a .
cp /Users/test1/curl/lib*-ioss-arm64.a .

