#!/bin/bash

make clean
make CFLAGS='-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -fembed-bitcode -g'
mv libsnifl.a libsnifl-ios-arm64.a

